name: deep-learning
channels:
- defaults
dependencies:
- appnope=0.1.0=py36_0
- cycler=0.10.0=py36_0
- decorator=4.0.11=py36_0
- entrypoints=0.2.2=py36_0
- freetype=2.5.5=2
- icu=54.1=0
- ipykernel=4.5.2=py36_0
- ipython=5.1.0=py36_1
- ipython_genutils=0.1.0=py36_0
- ipywidgets=5.2.2=py36_1
- jinja2=2.9.4=py36_0
- jsonschema=2.5.1=py36_0
- jupyter=1.0.0=py36_3
- jupyter_client=4.4.0=py36_0
- jupyter_console=5.0.0=py36_0
- jupyter_core=4.2.1=py36_0
- libpng=1.6.27=0
- markupsafe=0.23=py36_2
- matplotlib=2.0.0=np111py36_0
- mistune=0.7.3=py36_1
- mkl=2017.0.1=0
- nbconvert=4.2.0=py36_0
- nbformat=4.2.0=py36_0
- notebook=4.3.1=py36_0
- numpy=1.11.3=py36_0
- openssl=1.0.2k=0
- pandas=0.19.2=np111py36_1
- path.py=10.0=py36_0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_1
- prompt_toolkit=1.0.9=py36_0
- ptyprocess=0.5.1=py36_0
- pygments=2.1.3=py36_0
- pyparsing=2.1.4=py36_0
- pyqt=5.6.0=py36_2
- python=3.6.0=0
- python-dateutil=2.6.0=py36_0
- pytz=2016.10=py36_0
- pyzmq=16.0.2=py36_0
- qt=5.6.2=0
- qtconsole=4.2.1=py36_1
- readline=6.2=2
- setuptools=27.2.0=py36_0
- simplegeneric=0.8.1=py36_1
- sip=4.18=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- terminado=0.6=py36_0
- tk=8.5.18=0
- tornado=4.4.2=py36_0
- traitlets=4.3.1=py36_0
- wcwidth=0.1.7=py36_0
- wheel=0.29.0=py36_0
- widgetsnbextension=1.2.6=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.1
  - prompt-toolkit==1.0.9
prefix: /Users/myMac/anaconda/envs/deep-learning

